site_name: Lockbox Extension
site_description: Documentation for the Firefox extension
theme: readthedocs
repo_url: https://github.com/mozilla-lockbox/lockbox-extension

extra_css:
- css/extra.css

markdown_extensions:
- attr_list
- admonition

pages:
- 'Introduction': 'index.md'
- 'Release Notes': 'release-notes.md'
- 'FAQs': 'faqs.md'
- 'Contribute': 'contributing.md'
- 'Telemetry and Metrics': 'metrics.md'
- 'Developer Guides':
  - 'Build and Install': 'install.md'
  - 'Release Instructions': 'releases.md'
  - 'Test Plan': 'test-plan.md'
  - 'Test Plan - Accessibility': 'accessibility-test-plan.md'
  - 'Test Plan - Telemetry': 'telemetry-test-plan.md'
